version: "3.9"


services:
    postgres:
      container_name: postgres_container
      image: postgres
      environment:
          POSTGRES_USER: postgres
          POSTGRES_PASSWORD: 12345
          PGDATA: /data/postgres
      volumes:
        - postgres:/data/postgres
      ports:
        - "5432:5432"
      restart: unless-stopped



    api_db_admin:
      container_name: db_admin
      image: mongo-express
      environment:
        ME_CONFIG_MONGODB_ADMINUSERNAME: ${DB_ADMIN}
        ME_CONFIG_MONGODB_ADMINPASSWORD: ${DB_PASSWORD}
        ME_CONFIG_MONGODB_URL: ${DB_URI}
        ME_CONFIG_BASICAUTH_USERNAME: ${DB_ADMIN_UI_USER}
        ME_CONFIG_BASICAUTH_PASSWORD: ${DB_ADMIN_UI_PASSWORD}
      ports:
        - 8080:8081

    api_db:
      container_name: db
      image: mongo:4.4.19-rc0-focal
      volumes:
        - db-data:/data/db
        - ./src:/examples
      environment:
        MONGO_INITDB_ROOT_USERNAME: ${DB_ADMIN}
        MONGO_INITDB_ROOT_PASSWORD: ${DB_PASSWORD}
      ports:
        - 27017:27017


volumes:
    postgres:
    db-data: